site_name: DocuSnap-Frontend Architecture Documentation
site_description: Comprehensive architecture documentation for the DocuSnap-Frontend Android application
site_author: Ziming Zhou

# Repository
repo_name: JI-DeepSleep/DocuSnap-Frontend
repo_url: https://github.com/JI-DeepSleep/DocuSnap-Frontend

# Theme configuration
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    primary: indigo
    accent: indigo
  logo: images/logo.png

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Navigation structure
nav:
  - Home: index.md
  - Project Overview:
    - Business Background: overview/business-background.md
    - Core Features: overview/core-features.md
  - Technology Stack:
    - Technology Selection: technology/technology-selection.md
    - Selection Rationale: technology/selection-rationale.md
  - Architecture Design:
    - Overall Architecture: architecture/overall-architecture.md
    - MVVM Implementation: architecture/mvvm-implementation.md
    - Architecture Analysis: architecture/architecture-analysis.md
  - Core Modules:
    - Document Processing: modules/document-processing.md
    - Form Processing: modules/form-processing.md
    - Image Processing: modules/image-processing.md
    - Backend Communication: modules/backend-communication.md
    - Module Interactions: modules/module-interactions.md
  - Typical Processes:
    - Document Scanning: processes/document-scanning.md
    - Form Field Extraction: processes/form-field-extraction.md
    - Key Business Processes: processes/key-business-processes.md
  - Code Quality Assessment:
    - Code Structure: quality/code-structure.md
    - Design Patterns: quality/design-patterns.md
    - Strengths and Improvements: quality/strengths-improvements.md
  - Deployment Architecture:
    - Deployment Topology: deployment/deployment-topology.md
    - Technology Stack Dependencies: deployment/technology-dependencies.md
    - Deployment Strategy: deployment/deployment-strategy.md
  - Summary and Recommendations:
    - Architecture Advantages: summary/architecture-advantages.md
    - Quick Start Guide: summary/quick-start-guide.md
    - Future Optimizations: summary/future-optimizations.md